### ISSUE TITLE
Support downloading media types that are not the Siren media type

### ISSUE THREAD

**Issue by miller79** [siren-js/api-browser#24]
If an endpoint takes you to a download, it would be nice for the link to provide an option to download it directly.  Another option would be for it to have a 4th option outside of raw and parsed to just download the raw version.

**Comment by dillonredding** [comment]
What if we have a download button on the Raw tab that initiates a download of the response content?

**Comment by miller79** [comment]
If anywhere, I think it should be on the first page.  That’s where you will probably be when you go there.

**Comment by dillonredding** [comment]
That's fair. We could just add a button to every tab. For non-Siren, the Pretty and Parsed tabs will have the error notification, so we can just slap a download button in there.

**Comment by dillonredding** [comment]
Check out the new **Download Content** menu option for this.

![image](https://github.com/siren-js/api-browser/assets/17882787/c0425ebc-f99e-4df3-af2a-61828a765d8d)

@miller79 it's not exactly what I had originally proposed, so let me know if it works for you.
